### ISSUE TITLE
github io 挂了

### ISSUE THREAD

**Issue by Dangerise** [zjp-CN/helix-book#2]
其他人的github io可以访问，但是似乎你的所有部署的东西都挂了

**Comment by zjp-CN** [comment]
没有啊。部署的 https://zjp-cn.github.io/helix-book/ 可以访问啊。

**Comment by Dangerise** [comment]
![Visit](https://github.com/zjp-CN/helix-book/assets/88434542/76f061a8-cc32-4d92-b616-1f8a5099e254)
@zjp-CN
